server.port=8097
spring.application.name=vd5-ajax-crud

spring.thymeleaf.cache=false

# --- SQL Server (dung chung server/user voi VD1-2 va VD3) ---
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS01;databaseName=webst2_ajax_crud;encrypt=false;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=iot_user
spring.datasource.password=27122006
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# --- Swagger3 / OpenAPI ---
springdoc.swagger-ui.path=/swagger-ui.html
